name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-contributors:
  - dependabot
template: |
  See the [CHANGELOG.md](https://github.com/$OWNER/$REPOSITORY/blob/master/CHANGELOG.md) for more information.

  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
